apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-logs-pvc
  namespace: chaosblade
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client-storageclass
