# Extracted from: additionalPrometheusRulesMap.prometheus-aggregates
# Source: ../prometheus_stack-install/monitor-kube-prometheus-stack-values.yaml
groups:
  - name: prometheus-notification
    rules:
      - record: prometheus:notification_queue_utilization:ratio5m
        expr: avg_over_time(prometheus_notifications_queue_length{job="monitor-kube-prometheus-st-prometheus", namespace="monitor"}[5m]) / min_over_time(prometheus_notifications_queue_capacity{job="monitor-kube-prometheus-st-prometheus", namespace="monitor"}[5m])
      - record: prometheus:notification_error_sendingalerts_to_alertmanger:ratio5m
        expr: rate(prometheus_notifications_errors_total{job="monitor-kube-prometheus-st-prometheus",namespace="monitor"}[5m]) / rate(prometheus_notifications_sent_total{job="monitor-kube-prometheus-st-prometheus",namespace="monitor"}[5m])
      - record: prometheus:notification_connect_alertmanger:5m
        expr: max_over_time(prometheus_notifications_alertmanagers_discovered{job="monitor-kube-prometheus-st-prometheus",namespace="monitor"}[5m])
      - record: prometheus:notification_error:ratio5m
        expr: rate(prometheus_notifications_errors_total{job="monitor-kube-prometheus-st-prometheus",namespace="monitor"}[5m]) / rate(prometheus_notifications_sent_total{job="monitor-kube-prometheus-st-prometheus",namespace="monitor"}[5m])
  - name: prometheus-sd
    rules:
      - record: prometheus:sd:targets:sum
        expr: sum by (cluster) (max without (instance, pod, endpoint, service, job, namespace, name, config, prometheus, replica) (prometheus_sd_discovered_targets{name="scrape"}))
      - record: prometheus:sd:issues:increase5m
        expr: sum by (cluster) (max without (instance, pod, endpoint, service, job, namespace, name, config, prometheus, replica) (increase(prometheus_sd_kubernetes_failures_total[5m]))) + sum by (cluster) (max without (instance, pod, endpoint, service, job, namespace, name, config, prometheus, replica) (increase(prometheus_sd_updates_delayed_total[5m])))
  - name: prometheus-remotewirte
    rules:
      - record: prometheus:remote_write:samples_retried:rate5m
        expr: sum by (cluster, remote_name, url) (rate(prometheus_remote_storage_samples_retried_total[5m]))
      - record: prometheus:remote_write:samples_failed:rate5m
        expr: sum by (cluster, remote_name, url) (rate(prometheus_remote_storage_samples_failed_total[5m]))
      - record: prometheus:remote_write:lag_seconds
        expr: (max by (cluster, remote_name) (prometheus_remote_storage_queue_highest_timestamp_seconds)) - (max by (cluster, remote_name) (prometheus_remote_storage_queue_highest_sent_timestamp_seconds))
