# =========================================================
# Job 1/5: API Auth
# run script：/scripts/api_auth.js
# depency：k6-gitea-api-auth
# =========================================================
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-gitea-api-auth-job
  namespace: traffic
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:0.49.0
          imagePullPolicy: IfNotPresent
          command: ["k6", "run", "/scripts/api_auth.js"]
          env:
            # ===== base connnection url =====
            - name: BASE_URL
              value: "https://gitea.example.com"
            - name: INSECURE_TLS
              value: "true"

            # ===== validation =====
            - name: GITEA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: k6-gitea-secret
                  key: token

            # ===== load parameters =====
            - name: VUS
              value: "1"
            - name: DURATION
              value: "30s"
            - name: SLEEP_SECONDS
              value: "1"

            # ===== pages =====
            - name: PAGES
              value: "1"
            - name: PER_PAGE
              value: "20"
            - name: ENABLE_USER_REPOS
              value: "true"

            # ===== thresholds =====
            - name: THRESH_FAIL_RATE
              value: "0.01"
            - name: THRESH_P95_MS
              value: "1200"
            - name: THRESH_CHECK_RATE
              value: "0.99"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: k6-gitea-api-auth-script
