apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k6-logs-pvc
  namespace: traffic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: nfs-client-storageclass
