apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-rt-preflight-env
  namespace: traffic
data:
  BASE_URL: "https://rt.example.com" # If RT has a WebPath prefix such as /rt, use https://rt.example.com/rt
  INSECURE_TLS: "true"
  RT_QUEUE: "Traffic"

  # User selection: by default use the first requester + first staff (you can change this to random)
  REQUESTER_INDEX: "0"
  STAFF_INDEX: "0"

  # Whether to perform delete in smoke tests (set to deleted)
  ENABLE_DELETE: "true"

  # Used to mark load-test data for later TicketSQL cleanup
  SUBJECT_PREFIX: "k6-rt-preflight"
