apiVersion: v1
kind: Secret
metadata:
  name: k6-wiki-secret
  namespace: traffic
type: Opaque
stringData:
  WIKI_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGkiOjEsImdycCI6MSwiaWF0IjoxNzY5MDEyNzk1LCJleHAiOjE4NjM2ODU1OTUsImF1ZCI6InVybjp3aWtpLmpzIiwiaXNzIjoidXJuOndpa2kuanMifQ.chbmtHG_hYpE7EsZ9QnwY1_TzR6z6oxVLeL4Hnwf3AHQbYIFxt3X_sjWHzC7hG5-fZPT5STKqC84ZG-e0kSE7TgVNxKN7XBKwMKUzJPc5gQXL1oTmHhxL3ZNhCgcPGNwN7wrew0N7fwL_45BWnWZXE7JEheCgVFBM6om2H3LFG1z3Ui5ey10dx8cRDUrI7tJpkCZVjAM7UFFNmXGFPAUrBB7x8JPgQyPkIwu6zv2m5ywdB3EogEpXWcrfn87Gnr5hJSI3jPCf12j8uMRwfCB5BwBkjUkxdy4IAII1S2mdEOlHQS7NzN8DG4Hy-eSwDJOc3lw4YXfYsVvxQQ1OwCK_A"
