apiVersion: v1
kind: Secret
metadata:
  name: minio-fluentbit-s3-credentials
  namespace: logging
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "<minio-access-key>"
  MINIO_SECRET_KEY: "<minio-secret-key>"
