apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluent-bit-logs
  namespace: logging
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: nfs-client-storageclass
  resources:
    requests:
      storage: 10Gi
