apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-http-redirect
  namespace: gitea
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: gitea-redirect-to-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: gitea.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-http
                port:
                  number: 3000
