# Root Credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-auth
  namespace: database
type: Opaque
stringData:
  rootUser: admin
  rootPassword: "<password>"
---
#  Provisioned User Credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-provision-users
  namespace: database
type: Opaque
stringData:
  fluentbit-user: |
    username=fluentbit
    password=<password>
    disabled=false
    policies=logs-rw
    setPolicies=true
