apiVersion: v1
kind: Secret
metadata:
  name: pg-cluster-auth
  namespace: database
type: Opaque
stringData:
  postgres-password: "<postgres-password>"
  replication-password: "<replication-password>"
  password: "<application-user-password>"
