global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""
  security:
    allowInsecureImages: false
  postgresql:
    fullnameOverride: ""
    auth:
      postgresPassword: ""
      username: ""
      password: ""
      database: ""
      existingSecret: ""
      secretKeys:
        adminPasswordKey: ""
        userPasswordKey: ""
        replicationPasswordKey: ""
    service:
      ports:
        postgresql: ""

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
clusterDomain: cluster.local
extraDeploy: []
commonLabels: {}
commonAnnotations: {}
secretAnnotations: {}

diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

auth:
  enablePostgresUser: true
  postgresPassword: ""
  username: ""
  password: ""
  database: ""
  replicationUsername: repl
  replicationPassword: ""
  existingSecret: pg-cluster-auth
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password
    replicationPasswordKey: replication-password
  usePasswordFiles: true

architecture: replication

replication:
  synchronousCommit: "off"
  numSynchronousReplicas: 0
  applicationName: my_application

containerPorts:
  postgresql: 5432

audit:
  logHostname: false
  logConnections: false
  logDisconnections: false
  pgAuditLog: ""
  pgAuditLogCatalog: "off"
  clientMinMessages: error
  logLinePrefix: ""
  logTimezone: ""

ldap:
  enabled: false
  server: ""
  port: ""
  prefix: ""
  suffix: ""
  basedn: ""
  binddn: ""
  bindpw: ""
  searchAttribute: ""
  searchFilter: ""
  scheme: ""
  tls:
    enabled: false
  uri: ""

postgresqlDataDir: /bitnami/postgresql/data
# postgresqlSharedPreloadLibraries: "pgaudit"
postgresqlSharedPreloadLibraries: ""

shmVolume:
  enabled: true
  sizeLimit: "128Mi"

tls:
  enabled: false
  autoGenerated: false
  preferServerCiphers: true
  certificatesSecret: ""
  certFilename: ""
  certKeyFilename: ""
  certCAFilename: ""
  crlFilename: ""

primary:
  name: primary
  configuration: ""
  pgHbaConfiguration: ""
  existingConfigmap: ""
  extendedConfiguration: |
    max_connections = 50
    shared_buffers = 128MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
  existingExtendedConfigmap: ""
  initdb:
    args: ""
    postgresqlWalDir: ""
    scripts: {}
    scriptsConfigMap: ""
    scriptsSecret: ""
    user: ""
    password: ""
  preInitDb:
    scripts: {}
    scriptsConfigMap: ""
    scriptsSecret: ""
  standby:
    enabled: false
    primaryHost: ""
    primaryPort: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  command: []
  args: []
  resourcesPreset: none
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  automountServiceAccountToken: false
  hostAliases: []
  hostNetwork: false
  hostIPC: false
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  affinity: {}
  nodeSelector:
    node-role: worker
  tolerations: []
  topologySpreadConstraints: []
  priorityClassName: ""
  schedulerName: ""
  runtimeClassName: ""
  terminationGracePeriodSeconds: ""
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  extraVolumeMounts: []
  extraVolumes: []
  sidecars: []
  initContainers: []
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""
  extraPodSpec: {}
  networkPolicy:
    enabled: false
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []
    ingressNSMatchLabels: {}
    ingressNSPodMatchLabels: {}
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
    nodePorts:
      postgresql: ""
    clusterIP: ""
    labels: {}
    annotations: {}
    loadBalancerClass: ""
    loadBalancerIP: ""
    externalTrafficPolicy: Cluster
    loadBalancerSourceRanges: []
    extraPorts: []
    sessionAffinity: None
    sessionAffinityConfig: {}
    headless:
      annotations: {}
  persistence:
    enabled: true
    volumeName: data
    existingClaim: ""
    mountPath: /bitnami/postgresql
    subPath: ""
    storageClass: nfs-client-storageclass
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    annotations: {}
    labels: {}
    selector: {}
    dataSource: {}
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Retain

readReplicas:
  name: read
  replicaCount: 1
  extendedConfiguration: |
    max_connections = 50
    shared_buffers = 128MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  command: []
  args: []
  resourcesPreset: none
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  automountServiceAccountToken: false
  hostAliases: []
  hostNetwork: false
  hostIPC: false
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  affinity: {}
  nodeSelector:
    node-role: worker
  tolerations: []
  topologySpreadConstraints: []
  priorityClassName: ""
  schedulerName: ""
  runtimeClassName: ""
  terminationGracePeriodSeconds: ""
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: {}
  extraVolumeMounts: []
  extraVolumes: []
  sidecars: []
  initContainers: []
  pdb:
    create: true
    minAvailable: ""
    maxUnavailable: ""
  extraPodSpec: {}
  networkPolicy:
    enabled: false
    allowExternal: true
    allowExternalEgress: true
    extraIngress: []
    extraEgress: []
    ingressNSMatchLabels: {}
    ingressNSPodMatchLabels: {}
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
    nodePorts:
      postgresql: ""
    clusterIP: ""
    labels: {}
    annotations: {}
    loadBalancerClass: ""
    loadBalancerIP: ""
    externalTrafficPolicy: Cluster
    loadBalancerSourceRanges: []
    extraPorts: []
    sessionAffinity: None
    sessionAffinityConfig: {}
    headless:
      annotations: {}
  persistence:
    enabled: true
    existingClaim: ""
    mountPath: /bitnami/postgresql
    subPath: ""
    storageClass: nfs-client-storageclass
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    annotations: {}
    labels: {}
    selector: {}
    dataSource: {}
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Retain

backup:
  enabled: false

passwordUpdateJob:
  enabled: false

volumePermissions:
  enabled: false

serviceBindings:
  enabled: false

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: false
  annotations: {}

rbac:
  create: false
  rules: []

psp:
  create: false

metrics:
  enabled: false
