apiVersion: v1
kind: Secret
metadata:
  name: rt-secrets
  namespace: rt
type: Opaque
stringData:
  RT_DB_HOST: "pg-postgresql-primary.database.svc.cluster.local"
  RT_DB_PORT: "5432"
  RT_DB_NAME: "rt"
  RT_DB_USER: "rt"
  RT_DB_PASS: "rt123!"
  RT_ROOT_PASSWORD: "root123!"
  RT_WEB_DOMAIN: "rt.example.com"
  RT_WEB_PORT: "443"
  RT_WEB_PATH: ""
  RT_RTNAME: "rt.example.com"
  RT_ORGANIZATION: "example.com"
