apiVersion: v1
kind: Secret
metadata:
  name: postgresql-wiki-secret
  namespace: wiki
type: Opaque
stringData:
  DB_TYPE: "postgres"
  DB_HOST: "pg-postgresql-primary.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "wiki"
  DB_PASS: "wiki123!"
  DB_NAME: "wiki"
  DB_SSL: "false"
