apiVersion: v1
data:
  htpasswd: YWRtaW46JDJ5JDA1JGl3QmdkaGtSay8uT0lUd3k2RmFiZ2VZZkhBM2JsUUNUemdkRDJXNVJjVVoxZVpGaUhCMDdlCgp1c2VyOiQyeSQwNSRPR211dGNSaXZkV1VFN1VpWDBIaU5lTko0M3BZa0VPTGFUaUpGN0w0ak5NR1NvU280ODFwUwoK
kind: Secret
metadata:
  creationTimestamp: null
  name: zot-htpasswd
  namespace: zot
